language: rust
rust:
    - stable
jobs:
    include:
        - env: TARGET=x86_64-apple-darwin
          os: osx
        - env: TARGET=x86_64-pc-windows-msvc
        - env: TARGET=x86_64-unknown-linux-gnu
cache: cargo
script:
    - cargo test --verbose --all --target $TARGET
    - cargo build --verbose --all --release --target $TARGET
