name: Rust

on:
  push:
    tags: 
      - 'v*'

env:
  CARGO_TERM_COLOR: always
  NAME: vocabulist
  BINARY_NAME: vocabulist_rs

jobs:
  deploy:
    name: Deploy from ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
      
    - name: Cache Cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
    - name: Set Target MacOS
      if: matrix.os == 'macos-latest'
      run: echo "::set-env name=TARGET::x86_64-apple-darwin"
      
    - name: Set Target Linux
      if: matrix.os == 'ubuntu-latest'
      run: echo "::set-env name=TARGET::x86_64-unknown-linux-gnu"
    
    - name: Build Release
      run: cargo build --verbose --release --workspace --target $TARGET
      
    - name: Set Tag
      run: echo "::set-env name=TAG::${{ github.event.release.tag_name }}"
      
    - name: Package Release Linux 
      run: |
        src_path="$(pwd)"
        stage_path="staging_directory"
        package_path="$stage_path/$NAME"
        package="$NAME"
        
        mkdir -p $package_path
        
        cp target/$TARGET/release/$BINARY_NAME $package_path
        cp jmdict.db $package_path
        cp ACKNOWLEDGEMENTS.md $package_path
        cp LICENSE.md $package_path
        
        cd $stage_path
        
        tar czf "$src/$NAME-$TAG-$TARGET.tar.gz" $package
    
    - name: Create a Release
      uses: actions/create-release@v1
      with:
        # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
        tag_name: ${{ github.ref }}
        # The name of the release. For example, `Release v1.0.1`
        release_name: Release ${{ github.ref }}
