name: Rust

on:
  push:
    tags: 
      - 'v*'

env:
  CARGO_TERM_COLOR: always
  NAME: vocabulist
  BINARY_NAME: vocabulist_rs

jobs:
  deploy:
    name: Deploy from ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
      
    - name: Cache Cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
    - name: Set Target MacOS
      if: matrix.os == 'macos-latest'
      run: echo "::set-env name=TARGET::x86_64-apple-darwin"
      
    - name: Set Target Linux
      if: matrix.os == 'ubuntu-latest'
      run: echo "::set-env name=TARGET::x86_64-unknown-linux-gnu"
    
    - name: Build Release
      run: cargo build --verbose --release --workspace --target $TARGET
      
    - name: Set Tag
      run: echo "::set-env name=TAG::${{ github.ref }}"
      
    - name: Package Release Linux 
      id: package_archive
      run: |
        src_path="$(pwd)"

        stage_path="staging_directory"
        package_path="$stage_path/$NAME"
        package="$NAME"

        share_path="$package_path/$package"

        tag="$(basename $TAG)"

        archive_name="$NAME-$tag-$TARGET.tar.gz"

        echo "::set-output name=tag::${tag}"
        echo "::set-output name=archive_name::${archive_name}"

        mkdir -p $package_path
        mkdir "$share_path"    # /usr/local/share/vocabulist
        
        cp target/$TARGET/release/$BINARY_NAME $package_path
        cp jmdict.db $share_path
        cp ACKNOWLEDGEMENTS.md $package_path
        cp LICENSE.md $package_path
        
        cd $stage_path
        
        tar czf "${src_path}/${archive_name}" "${package}"

        cd $src_path
    
    - name: Upload the Assets
      id: create_release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ steps.package_archive.outputs.archive_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
