name: Rust

on:
  push:
    tags: 
      - 'v*'

env:
  CARGO_TERM_COLOR: always
  NAME: vocabulist
  BINARY_NAME: vocabulist_rs

jobs:
  deploy:
    name: Deploy from ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
      
    - name: Cache Cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
    - name: Set Target MacOS
      if: matrix.os == 'macos-latest'
      run: echo "::set-env name=TARGET::x86_64-apple-darwin"
      
    - name: Set Target Linux
      if: matrix.os == 'ubuntu-latest'
      run: echo "::set-env name=TARGET::x86_64-unknown-linux-gnu"
    
    - name: Build Release
      run: cargo build --verbose --release --workspace --target $TARGET
      
    - name: Set TAG_PATH
      run: echo "::set-env name=TAG_PATH::${{ github.ref }}"
      
    - name: Package Release Linux 
      id: package_archive
      run: |
        src_path="$(pwd)"

        stage_path="staging_directory"
        package_path="$stage_path/$NAME"
        package="$NAME"

        tag="$(basename $TAG_PATH)"

        archive_name="$NAME-$tag-$TARGET.tar.gz"

        echo "::set-output name=tag::${tag}"
        echo "::set-output name=archive_name::${archive_name}"

        echo "::set-env name=TAG::${tag}"

        mkdir -p $package_path
        
        cp target/$TARGET/release/$BINARY_NAME $package_path
        cp jmdict.db $package_path
        cp ACKNOWLEDGEMENTS.md $package_path
        cp LICENSE.md $package_path
        
        cd $stage_path
        
        tar czf "${src_path}/${archive_name}" "${package}"

        cd $src_path

    - name: Upload the Assets
      id: create_release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ steps.package_archive.outputs.archive_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set HASH 
      run: |
        hash="$(shasum -a 256 ${{ steps.package_archive.outputs.archive_name }})"
        echo "::set-env name=HASH::${hash}"
        
    - name: Set FORMULA_PATH
      run: echo "::set-env name=FORMULA_PATH::homebrew-vocabulist/Formula/vocabulist.rb"

    - name: Update Formula
      run: |
        repo="https://odakaui:${{ secrets.PAT }}@github.com/odakaui/homebrew-vocabulist.git"
        git clone "${repo}" "homebrew-vocabulist"

        python3 ci/update_homebrew_formula.py
        
        cd "homebrew-vocabulist/Formula"

        tag="${{ steps.package_archive.outputs.tag }}"

        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

        git add .
        git commit -am "Version ${tag:1}"
        git push "${repo}" master
